# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Compilation CMake multi-platform

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cmake_version: [3.21.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        curl -L https://github.com/Kitware/CMake/releases/download/v${{ matrix.cmake_version }}/cmake-${{ matrix.cmake_version }}-$(uname -s)-$(uname -m).tar.gz | tar --strip-components=1 -xz -C /usr/local
        cmake --version
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'

    - name: Install CMake (Windows)
      run: |
        choco install cmake --version ${{ matrix.cmake_version }}
        cmake --version
      if: matrix.os == 'windows-latest'

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'

    - name: Configure and build (Windows)
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
      if: matrix.os == 'windows-latest'
