# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Compilation CMake multi-platform

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cmake_version: [3.21.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake
        cmake --version

    - name: Debug
      run: |
        ls -R
        pwd
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'


    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build .
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
