# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Compilation CMake multi-platform

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cmake_version: [3.21.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake
      if: matrix.os == 'ubuntu-latest'
      uses: cmake/setup-cmake@v1
      with:
        cmake-version: ${{ matrix.cmake_version }}
        path-to-cmake: /usr/local/bin/cmake  # Adjust the path as needed

    - name: Install CMake (macOS)
      if: matrix.os == 'macOS-latest'
      run: brew install cmake

    - name: Install CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install cmake --version ${{ matrix.cmake_version }} --install-arguments 'ADD_CMAKE_TO_PATH=System'

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'

    - name: Configure and build (Windows)
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
      if: matrix.os == 'windows-latest'
